version: '3.3'

services:
  apimaster:
    image: toto_api_master:0.1.6
    build: "."
    ports:
      - "7074"
    restart: "always"
    networks:
      - "totoapimaster.network"
    deploy:
      replicas: 3
      restart_policy:
        max_attempts: 3
        condition: on-failure       
      update_config:
        parallelism: 3
        delay: 10s
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - apimaster
    ports:
      - "7073:7073"
    restart: always
    networks:
      - "totoapimaster.network"
networks:
  totoapimaster.network: